Repository goerli/testnet, pull requests merged in 2018-11, with the labels that each got.

#24 Update README.md
  README.md
Labels: A8-looksgood 🦄, M3-docs 📑

#25 Translate README.md to spanish
  README[Spanish].md
Labels: A2-insubstantial 👶, M3-docs 📑

#29 add static-nodes
  README.md
  geth/static-nodes.json
Labels: A8-looksgood 🦄, M2-config 📂, M3-docs 📑
